"""Renamed is_active to is_active_flag

Revision ID: 776618fcfccd
Revises: ebecf2901bc4
Create Date: 2025-04-11 11:30:47.138853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776618fcfccd'
down_revision = 'ebecf2901bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active_flag')

    # ### end Alembic commands ###
